language: php

sudo: false

php:
  - php: 5.5
  - php: 5.6
  - php: 7.0

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/cphalcon

services:
#  - memcached
#  - redis-server
  - mysql

before_install:
  - composer install --prefer-source --no-interaction
  - vendor/bin/install-phalcon.sh

before_script:
  - composer self-update
  - composer update --no-interaction --prefer-source
  - mysql -uroot -e 'CREATE DATABASE `phwoolcon_test` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci */;'

script:
  - phpunit --verbose
